### ISSUE TITLE
Would be great if this preserved newlines by encoding to `%0A`

### ISSUE THREAD

**Issue by spoelstraethan** [flesler/vscode-url-encode#1]
I was trying to use this extension to share some code that had line comments, without the newline encoding everything after the first `//` ended up being ignored, so I had to use urlencode.io or something like that to get a version that kept the newlines.

**Comment by flesler** [comment]
It's actually implemented, you can change the behavior by switching `url-encode.encodeWhitespace` to `true` in your VS Code configuration
